name:                honesty-box
version:             0.1.0.0
github:              "githubuser/honesty-box"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

default-extensions:
- OverloadedStrings

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/honesty-box#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  honesty-box-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - honesty-box
dependencies:
- base
- servant
- servant-server
- servant-auth
- servant-auth-server
- servant-client
- transformers
- aeson
- wai
- warp
- wai-cors
- bytestring
- http-client
- containers
- time
- sqlite-simple
- turtle
- resource-pool
#- db-notes

tests:
  honesty-box-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - honesty-box
    - hspec
    - example-servant-minimal
    - servant-client
    - warp >= 3.2.4
    - http-client
    - http-types
